# Day 13

Part 1:

The first section is a list of dots on the transparent paper. 0,0 represents the top-left coordinate. The first value, x, increases to the right. The second value, y, increases downward. So, the coordinate 3,0 is to the right of 0,0, and the coordinate 0,7 is below 0,0. The coordinates in this example form the following pattern, where # is a dot on the paper and . is an empty, unmarked position:

Then, there is a list of fold instructions. Each instruction indicates a line on the transparent paper and wants you to fold the paper up (for horizontal y=... lines) or left (for vertical x=... lines). In this example, the first fold instruction is fold along y=7, which designates the line formed by all of the positions where y is 7 (marked here with -):



In [8]:
import pandas as pd
import numpy as np
import math

In [88]:
#read in coordinates to populate matrix
test = pd.read_csv('day13_test.csv')
test

x   y
0    6  10
1    0  14
2    9  10
3    0   3
4   10   4
5    4  11
6    6   0
7    6  12
8    4   1
9    0  13
10  10  12
11   3   4
12   3   0
13   8   4
14   1  10
15   2  14
16   8  10
17   9   0

In [226]:
def create_matrix(df):
    #creates an empty matrix of zeros based on size of coordinates and then populates them with 1s based on
    #coordinates provided
    matrix = np.zeros((max(df['y'])+1,max(df['x'])+1))
    for i in df.index:
        matrix[df.loc[i]['y']][df.iloc[i]['x']] = 1
    return matrix

def horizontal_fold(num, matrx):
    #folds along y axis
    x=1
    while x < num+1:
        #adds up values when folding and applies to upper half above fold line
        matrx[num-x] = matrx[num+x]+matrx[num-x]
        x+=1
    #now we need to remove everything past fold line
    
    #remove values below fold line after we sum up
    matrx = matrx[0:num]
    
    #since we are doing a hard sum, we are resetting them all to 1
    for i in range(len(matrx[0])):
        for j in range(len(matrx)):
            if matrx[j][i] > 1: 
                matrx[j][i] = 1
            
    return matrx

def vertical_fold(num, matrx):
    #folds along x axis
    z=1
    while z < (math.floor(len(matrx[0])/2)+1):
        #sum up values on both sides of fold
        for t in range(len(matrx)):
            matrx[t][num-z] = matrx[t][num-z]+matrx[t][num+z]
        z+=1
    
    new_matrix = list()
    for i in range(len(matrx)):
        new_matrix.append(matrx[i][0:num])

    for i in range(len(new_matrix[0])):
        for j in range(len(new_matrix)):
            if new_matrix[j][i] > 1: 
                new_matrix[j][i] = 1
    return new_matrix
    
def sum_up(matrx):
    #loops through whole matrix and sums up all the values where there is a 1
    sum_val=0
    for i in range(len(matrx[0])):
            for j in range(len(matrx)):
                sum_val += matrx[j][i]
    return sum_val

In [227]:
#with the test set we match 16 and a square in the matrix
z = create_matrix(test)
y = horizontal_fold(7, z)
x = vertical_fold(5,y)
sum_up(x)

16.0

In [34]:
#now that the test lines up, we are ready for our actual data
data = pd.read_csv('day13.csv')
data

x    y
0      92  632
1     795    9
2    1034  368
3    1230  233
4     969  816
..    ...  ...
923   856  518
924   728  257
925   723  325
926   833  773
927   211  415

[928 rows x 2 columns]

In [228]:
# fold along x=655

matrx = create_matrix(data)
pt1 = vertical_fold(655, matrx)
sum_up(pt1)


790.0

In [298]:
len(pt1)

893

In [301]:
len(pt1[0:446])

446

In [304]:
len(pt1[447:892])

445

Answer is 790 for Part 1

In [275]:
#needs to be revised from test as it doesn't seem to line up to index 
#by using the max value +1

def horizontal_fold(num, matrx):
    x=1
    num=num-1
    while x < num+1:
        #adds up values when folding and applies to upper half above fold line
        matrx[num-x] = matrx[num+x]+matrx[num-x]
        x+=1
    
    #now we need to remove everything past fold line
    
    #remove values below fold line after we sum up
    matrx = matrx[0:num]
        
    #since we are doing a hard sum, we are resetting them all to 1
    for i in range(len(matrx[0])):
        for j in range(len(matrx)):
            if matrx[j][i] > 1: 
                matrx[j][i] = 1
            
    return matrx

In [276]:
# fold along y=447
t= horizontal_fold(447, pt1)

# fold along x=327
q = vertical_fold(327, t)

# fold along y=223
f = horizontal_fold(223, q)

# fold along x=163
d = vertical_fold(163, f)

# fold along y=111
r = horizontal_fold(111,d)

# fold along x=81
m = vertical_fold(81,r)

# fold along y=55
p = horizontal_fold(55,m)

# fold along x=40
h = vertical_fold(40,p)

# fold along y=27; looks to be something happening between n and b
n = horizontal_fold(27,h)

# fold along y=13
b = horizontal_fold(13,n)

# # fold along y=6
v = horizontal_fold(6,b)

In [277]:
revised_matrix = list()

x=0
while x < len(v):
    revised_matrix.append(v[x].astype(int))
    x+=1

np.savetxt('test.txt', revised_matrix)

#looking at final result, every 4 columns is a letter and then there is
#a break of 0s. So looping through every 4 columns will give us our
#code

In [284]:
#this returns an 8 digit set of characters
x=0
y=4

while y < len(revised_matrix[0]):
    for i in range(len(revised_matrix)):
        print(revised_matrix[i][x:y])
    print()
    x+=5
    y+=5

[1 1 1 1]
[1 1 1 1]
[1 0 0 1]
[1 1 1 0]
[1 0 0 0]

[1 1 1 0]
[1 0 1 1]
[1 0 0 1]
[1 1 1 1]
[1 0 0 1]

[1 1 0 1]
[1 0 0 1]
[1 1 1 1]
[1 0 0 1]
[1 0 0 1]

[1 1 1 1]
[0 1 0 1]
[1 0 1 0]
[1 1 1 1]
[1 0 0 0]

[1 1 1 0]
[1 0 0 1]
[1 1 1 1]
[1 1 1 1]
[1 0 0 1]

[1 1 1 1]
[1 0 0 0]
[1 1 1 0]
[1 0 0 0]
[1 0 0 0]

[0 0 1 1]
[0 0 0 1]
[1 0 0 1]
[0 1 1 1]
[1 0 0 1]

[1 1 1 0]
[1 0 0 1]
[1 0 0 1]
[1 1 1 0]
[1 0 0 1]

